[package]
name = "noiter"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.release_lto]
inherits = "release"
lto = true
strip = true
panic = "abort"
codegen-units = 1
opt-level = 3

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 1

[features]
default = ["fps", "debug"]
colliders = []
fps = ["bevy/bevy_dev_tools"]
debug = ["bevy/debug"]
tracy = ["bevy/trace_tracy"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = {version = "0.19.0", default-features = false, features = ["2d", "ui", "bevy_settings"]}
avian2d = {version = "0.7.0", features = ["simd", "parallel"]}
shapes = {version = "0.1.0", git = "https://github.com/bgkillas/helix"}
uninit_map = {version = "0.1.0", git = "https://github.com/bgkillas/helix"}
rand = { version = "0.10.1", default-features = false, features = ["std", "alloc", "simd_support", "sys_rng"] }

[lints.clippy]
pedantic = {level = "warn", priority = -1}
shadow_reuse = "warn"
unused_trait_names = "warn"
missing_inline_in_public_items = "warn"
str-to-string = "warn"
missing_panics_doc = "allow"
missing_errors_doc = "allow"
too_many_lines = "allow"
missing_fields_in_debug = "allow"
missing_safety_doc = "allow"
similar-names = "allow"
too_many_arguments = "allow"
type_complexity = "allow"
missing-inline-in-public-items = "allow"
needless_pass_by_value = "allow"

cast_precision_loss = "allow"
as_conversions = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"